# Generated by Django 5.2.5 on 2025-09-01 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Weather_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='city',
            table='Cityname',
        ),
    ]
